name: Docker Build & Push Simapp (main)
# Build & Push builds the simapp docker image on every push to main and
# and pushes the image to https://ghcr.io/cosmos/ibc-go-simd
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker.yml'
      - '**.go'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ibc-go-simd

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
      with:
        images: ${{ env.REGISTRY }}/cosmos/${{ env.IMAGE_NAME }}

    - name: Build Docker image
      uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          IBC_GO_VERSION=main

    - name: Test simd is runnable
      run: |
        docker run --rm ${{ steps.meta.outputs.tags }}
    - name: Log in to the Container registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          IBC_GO_VERSION=main
